name: Deployment cleanup

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  cleanup:
    if: contains(github.event.pull_request.labels.*.name, 'deploy')
    steps:
    - run: make jcdc-undeploy-goat
      env:
        REF: ${{ github.sha }}
        DEV: pr${{ github.event.number }}
        JCDC_URL: https://jcdc.jul.run/run
        JCDC_API_KEY: ${{ secrets.GOAT_JCDC_API_KEY }}
        DOCKER_TAG: pr${{ github.event.number }}
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

