name: Undeploy PR

on:
  pull_request:
    types: [closed]

jobs:
  undeploy:
    name: Undeploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make jcdc-undeploy-goat
      env:
        COMMIT_SHA: ${{ github.sha }}
        DEV: pr${{ github.event.number }}
        JCDC_URL: https://jcdc.jul.run/run
        JCDC_API_KEY: ${{ secrets.GOAT_JCDC_API_KEY }}
